---
- name: Check Service Status
  hosts: home_server
  become: yes

  vars:
    systemd_service_name: "calendar_alert_bot"

  tasks:
    - name: Get service status
      systemd:
        name: "{{ systemd_service_name }}"
      register: service_status

    - name: Show service status
      debug:
        msg: |
        msg: "{{ service_status.status | dict2items | selectattr('key', 'in', ['ActiveState','SubState','MainPID']) | items2dict }}"

    - name: Check recent logs for errors
      command: journalctl -u {{ systemd_service_name }} -n 20 --no-pager
      register: service_logs
      changed_when: false

    - name: Display recent logs
      debug:
        msg: "{{ service_logs.stdout_lines }}"

    - name: Fail if service is not running
      fail:
        msg: "Service {{ systemd_service_name }} is not active!"
      when: service_status.status.ActiveState != 'active'
      ignore_errors: yes
